version: '3.8'
services:
  web:
    image: ${IMAGE_NAME:-ghcr.io/nareshbaburoddam/nextcloud-php-dev}:${IMAGE_TAG:-latest}
    container_name: apache_php
    ports:
      - "82:80"
    volumes:
      - /mnt/s3-nextcloud-data:/var/www/html/nextcloud/data
    environment:
      MYSQL_HOST: database-1.c3eo066cexqf.ap-south-1.rds.amazonaws.com
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    restart: unless-stopped
