version: '3.8'
services:
  web:
    image: ${IMAGE_NAME:-ghcr.io/nareshbaburoddam/nextcloud-php-dev}:latest
    container_name: apache_php
    ports:
      - "82:80"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - /opt/nextcloud-data/mariadb:/var/lib/mysql
